### ISSUE TITLE
AF24/2.0 Firmware - 'DictDotLookup' object has no attribute 'dactemp0'

### ISSUE THREAD

**Issue by tbaschak** [zmousm/ubnt-nagios-plugins#1]
Any plans to update this for Airfiber 2.0 firmware?

Running nagios checks against a 2.0 firmware device gives errors about dactemp0:

```
UNKNOWN: 'DictDotLookup' object has no attribute 'dactemp0' - airfiber.rxpower0=-67 airfiber.rxpower1=-68 airfiber.rxcapacity=762792960 airfiber.txcapacity=727607040 airfiber.txmodrate=6 wireless.distance=4137  
```

**Comment by zmousm** [comment]
I am very sorry, I somehow managed to totally miss this issue...
I don't have access to AF 2.x devices currently. If you haven't fixed this already and can send me the json output of status.cgi, I would gladly take care of it.

**Comment by tbaschak** [comment]
I am also very sorry.. I no longer work with AirFibers at my current job. Hopefully someone else who runs 2.0 software will supply the json output from status.cgi

**Comment by zmousm** [comment]
I pushed a fix. This plugin surely needs a makeover in the longer term.
